yo jhipster:entity NoteSet
yo jhipster:entity NoteType
yo jhipster:entity Note
yo jhipster:entity Line
yo jhipster:entity TaxType
yo jhipster:entity Formulae
yo jhipster:entity Formula
yo jhipster:entity Addresses
yo jhipster:entity Address
yo jhipster:entity AddressLine
yo jhipster:entity Mill
yo jhipster:entity Quality
yo jhipster:entity SimpleGsmShade
yo jhipster:entity PriceList
yo jhipster:entity DerivedGsmShade
yo jhipster:entity Tax
yo jhipster:entity Price
yo jhipster:entity Customer
yo jhipster:entity CustomerGroup
