# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class Customer(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        Customer - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'addresses': 'Addresses',
            'code': 'str',
            'formulae': 'Formulae',
            'id': 'int',
            'name': 'str',
            'notes': 'NoteSet'
        }

        self.attribute_map = {
            'addresses': 'addresses',
            'code': 'code',
            'formulae': 'formulae',
            'id': 'id',
            'name': 'name',
            'notes': 'notes'
        }

        self._addresses = None
        self._code = None
        self._formulae = None
        self._id = None
        self._name = None
        self._notes = None

    @property
    def addresses(self):
        """
        Gets the addresses of this Customer.


        :return: The addresses of this Customer.
        :rtype: Addresses
        """
        return self._addresses

    @addresses.setter
    def addresses(self, addresses):
        """
        Sets the addresses of this Customer.


        :param addresses: The addresses of this Customer.
        :type: Addresses
        """
        self._addresses = addresses

    @property
    def code(self):
        """
        Gets the code of this Customer.


        :return: The code of this Customer.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """
        Sets the code of this Customer.


        :param code: The code of this Customer.
        :type: str
        """
        self._code = code

    @property
    def formulae(self):
        """
        Gets the formulae of this Customer.


        :return: The formulae of this Customer.
        :rtype: Formulae
        """
        return self._formulae

    @formulae.setter
    def formulae(self, formulae):
        """
        Sets the formulae of this Customer.


        :param formulae: The formulae of this Customer.
        :type: Formulae
        """
        self._formulae = formulae

    @property
    def id(self):
        """
        Gets the id of this Customer.


        :return: The id of this Customer.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Customer.


        :param id: The id of this Customer.
        :type: int
        """
        self._id = id

    @property
    def name(self):
        """
        Gets the name of this Customer.


        :return: The name of this Customer.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Customer.


        :param name: The name of this Customer.
        :type: str
        """
        self._name = name

    @property
    def notes(self):
        """
        Gets the notes of this Customer.


        :return: The notes of this Customer.
        :rtype: NoteSet
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """
        Sets the notes of this Customer.


        :param notes: The notes of this Customer.
        :type: NoteSet
        """
        self._notes = notes

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

