# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class ManagedUserDTO(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        ManagedUserDTO - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'activated': 'bool',
            'authorities': 'list[str]',
            'created_date': 'datetime',
            'email': 'str',
            'first_name': 'str',
            'id': 'int',
            'lang_key': 'str',
            'last_modified_by': 'str',
            'last_modified_date': 'datetime',
            'last_name': 'str',
            'login': 'str',
            'password': 'str'
        }

        self.attribute_map = {
            'activated': 'activated',
            'authorities': 'authorities',
            'created_date': 'createdDate',
            'email': 'email',
            'first_name': 'firstName',
            'id': 'id',
            'lang_key': 'langKey',
            'last_modified_by': 'lastModifiedBy',
            'last_modified_date': 'lastModifiedDate',
            'last_name': 'lastName',
            'login': 'login',
            'password': 'password'
        }

        self._activated = None
        self._authorities = None
        self._created_date = None
        self._email = None
        self._first_name = None
        self._id = None
        self._lang_key = None
        self._last_modified_by = None
        self._last_modified_date = None
        self._last_name = None
        self._login = None
        self._password = None

    @property
    def activated(self):
        """
        Gets the activated of this ManagedUserDTO.


        :return: The activated of this ManagedUserDTO.
        :rtype: bool
        """
        return self._activated

    @activated.setter
    def activated(self, activated):
        """
        Sets the activated of this ManagedUserDTO.


        :param activated: The activated of this ManagedUserDTO.
        :type: bool
        """
        self._activated = activated

    @property
    def authorities(self):
        """
        Gets the authorities of this ManagedUserDTO.


        :return: The authorities of this ManagedUserDTO.
        :rtype: list[str]
        """
        return self._authorities

    @authorities.setter
    def authorities(self, authorities):
        """
        Sets the authorities of this ManagedUserDTO.


        :param authorities: The authorities of this ManagedUserDTO.
        :type: list[str]
        """
        self._authorities = authorities

    @property
    def created_date(self):
        """
        Gets the created_date of this ManagedUserDTO.


        :return: The created_date of this ManagedUserDTO.
        :rtype: datetime
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """
        Sets the created_date of this ManagedUserDTO.


        :param created_date: The created_date of this ManagedUserDTO.
        :type: datetime
        """
        self._created_date = created_date

    @property
    def email(self):
        """
        Gets the email of this ManagedUserDTO.


        :return: The email of this ManagedUserDTO.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this ManagedUserDTO.


        :param email: The email of this ManagedUserDTO.
        :type: str
        """
        self._email = email

    @property
    def first_name(self):
        """
        Gets the first_name of this ManagedUserDTO.


        :return: The first_name of this ManagedUserDTO.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """
        Sets the first_name of this ManagedUserDTO.


        :param first_name: The first_name of this ManagedUserDTO.
        :type: str
        """
        self._first_name = first_name

    @property
    def id(self):
        """
        Gets the id of this ManagedUserDTO.


        :return: The id of this ManagedUserDTO.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ManagedUserDTO.


        :param id: The id of this ManagedUserDTO.
        :type: int
        """
        self._id = id

    @property
    def lang_key(self):
        """
        Gets the lang_key of this ManagedUserDTO.


        :return: The lang_key of this ManagedUserDTO.
        :rtype: str
        """
        return self._lang_key

    @lang_key.setter
    def lang_key(self, lang_key):
        """
        Sets the lang_key of this ManagedUserDTO.


        :param lang_key: The lang_key of this ManagedUserDTO.
        :type: str
        """
        self._lang_key = lang_key

    @property
    def last_modified_by(self):
        """
        Gets the last_modified_by of this ManagedUserDTO.


        :return: The last_modified_by of this ManagedUserDTO.
        :rtype: str
        """
        return self._last_modified_by

    @last_modified_by.setter
    def last_modified_by(self, last_modified_by):
        """
        Sets the last_modified_by of this ManagedUserDTO.


        :param last_modified_by: The last_modified_by of this ManagedUserDTO.
        :type: str
        """
        self._last_modified_by = last_modified_by

    @property
    def last_modified_date(self):
        """
        Gets the last_modified_date of this ManagedUserDTO.


        :return: The last_modified_date of this ManagedUserDTO.
        :rtype: datetime
        """
        return self._last_modified_date

    @last_modified_date.setter
    def last_modified_date(self, last_modified_date):
        """
        Sets the last_modified_date of this ManagedUserDTO.


        :param last_modified_date: The last_modified_date of this ManagedUserDTO.
        :type: datetime
        """
        self._last_modified_date = last_modified_date

    @property
    def last_name(self):
        """
        Gets the last_name of this ManagedUserDTO.


        :return: The last_name of this ManagedUserDTO.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """
        Sets the last_name of this ManagedUserDTO.


        :param last_name: The last_name of this ManagedUserDTO.
        :type: str
        """
        self._last_name = last_name

    @property
    def login(self):
        """
        Gets the login of this ManagedUserDTO.


        :return: The login of this ManagedUserDTO.
        :rtype: str
        """
        return self._login

    @login.setter
    def login(self, login):
        """
        Sets the login of this ManagedUserDTO.


        :param login: The login of this ManagedUserDTO.
        :type: str
        """
        self._login = login

    @property
    def password(self):
        """
        Gets the password of this ManagedUserDTO.


        :return: The password of this ManagedUserDTO.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """
        Sets the password of this ManagedUserDTO.


        :param password: The password of this ManagedUserDTO.
        :type: str
        """
        self._password = password

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

