# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class Note(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        Note - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'note_set': 'NoteSet',
            'type': 'NoteType'
        }

        self.attribute_map = {
            'id': 'id',
            'note_set': 'noteSet',
            'type': 'type'
        }

        self._id = None
        self._note_set = None
        self._type = None

    @property
    def id(self):
        """
        Gets the id of this Note.


        :return: The id of this Note.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Note.


        :param id: The id of this Note.
        :type: int
        """
        self._id = id

    @property
    def note_set(self):
        """
        Gets the note_set of this Note.


        :return: The note_set of this Note.
        :rtype: NoteSet
        """
        return self._note_set

    @note_set.setter
    def note_set(self, note_set):
        """
        Sets the note_set of this Note.


        :param note_set: The note_set of this Note.
        :type: NoteSet
        """
        self._note_set = note_set

    @property
    def type(self):
        """
        Gets the type of this Note.


        :return: The type of this Note.
        :rtype: NoteType
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Note.


        :param type: The type of this Note.
        :type: NoteType
        """
        self._type = type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

