# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class PriceList(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        PriceList - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'active': 'bool',
            'id': 'int',
            'wef_date_from': 'str',
            'wef_date_to': 'str'
        }

        self.attribute_map = {
            'active': 'active',
            'id': 'id',
            'wef_date_from': 'wefDateFrom',
            'wef_date_to': 'wefDateTo'
        }

        self._active = None
        self._id = None
        self._wef_date_from = None
        self._wef_date_to = None

    @property
    def active(self):
        """
        Gets the active of this PriceList.


        :return: The active of this PriceList.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """
        Sets the active of this PriceList.


        :param active: The active of this PriceList.
        :type: bool
        """
        self._active = active

    @property
    def id(self):
        """
        Gets the id of this PriceList.


        :return: The id of this PriceList.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this PriceList.


        :param id: The id of this PriceList.
        :type: int
        """
        self._id = id

    @property
    def wef_date_from(self):
        """
        Gets the wef_date_from of this PriceList.


        :return: The wef_date_from of this PriceList.
        :rtype: str
        """
        return self._wef_date_from

    @wef_date_from.setter
    def wef_date_from(self, wef_date_from):
        """
        Sets the wef_date_from of this PriceList.


        :param wef_date_from: The wef_date_from of this PriceList.
        :type: str
        """
        self._wef_date_from = wef_date_from

    @property
    def wef_date_to(self):
        """
        Gets the wef_date_to of this PriceList.


        :return: The wef_date_to of this PriceList.
        :rtype: str
        """
        return self._wef_date_to

    @wef_date_to.setter
    def wef_date_to(self, wef_date_to):
        """
        Sets the wef_date_to of this PriceList.


        :param wef_date_to: The wef_date_to of this PriceList.
        :type: str
        """
        self._wef_date_to = wef_date_to

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

